### ISSUE TITLE
Create Magine Lambda environment for QA and STG.

### ISSUE THREAD

**Issue by KempfCreative** [MaisonetteWorld/magine#50]
As part of the QA process in looking at the CMS, we (@mrosenwald and I) noticed that images were not uploading and saving. I did some digging and noticed that there are no environments for QA and STG, which would make it impossible to upload images!

Please help ASAP!

**Comment by DanRoestorf** [comment]
@KempfCreative We do have Magine setup for stg in the us-west-2 (Oregon) region: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/magine-stg?tab=graph

I'll go ahead and set that up for QA now.

Most likely image uploads aren't working because the endpoint hasn't been subscribed to the SNS topic: https://us-west-2.console.aws.amazon.com/sns/v3/home?region=us-west-2#/topic/arn:aws:sns:us-west-2:276428873250:magine-stg

What's the correct endpoint to subscribe?

**Comment by KempfCreative** [comment]
the strapi endpoint is the correct one

**Comment by DanRoestorf** [comment]
Documenting here in case I get stuck. Currently unable to subscribe the magine endpoint to an SNS topic.

Hitting the http://strapi.qa.env.maisonette.com/magine/update endpoint results in this error in Strapi logs:
```
services updateType true
services relation {}
[2019-09-30T15:56:24.363Z] error TypeError: Cannot destructure property `types` of 'undefined' or 'null'.
    at Object.update (/app/strapi/plugins/magine/services/Magine.js:61:9)
    at update (/app/strapi/plugins/magine/controllers/Magine.js:37:62)
    at dispatch (/app/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/app/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at dispatch (/app/strapi/node_modules/koa-compose/index.js:42:32)
    at policies.push (/app/strapi/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:28)
    at dispatch (/app/strapi/node_modules/koa-compose/index.js:42:32)
```

Hitting it as http gets this result in logs:
```
{ request:
   { method: 'GET',
     url: '/magine/update',
     header:
      { 'x-forwarded-for': '172.93.13.78',
        'x-forwarded-proto': 'https',
        'x-forwarded-port': '443',
        host: 'strapi.qa.env.maisonette.com',
        'x-amzn-trace-id': 'Root=1-5d9225f1-8499c760953895a002904000',
        'user-agent': 'PostmanRuntime/7.16.3',
        accept: '*/*',
        'cache-control': 'no-cache',
        'postman-token': '793519a6-0e23-4071-ab55-cfc7395f58ac',
        'accept-encoding': 'gzip, deflate',
        referer: 'http://strapi.qa.env.maisonette.com/magine/update' } },
  response:
   { status: 404,
     message: 'Not Found',
     header: [Object: null prototype] { vary: 'Origin' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/magine/update',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```

It reports a 404 response despite Postman receiving a 200
```
{
    "message": "ok"
}
```

**Comment by DanRoestorf** [comment]
Sending the confirmation request through SNS results in the same error. We can see the correct payload being delivered:
```
services updateType true
services relation {
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "2b1ad841-b235-461f-967a-befbb5afaeb5",
  "Token" : "2336412f37fb687f5d51e6e241dbca52e6afbffe988721d9c64b3691091f6078cb23594fa041543a4154a271d741e3d679257f3e6a814696f4adae1715dda06f91c6bf50a1d6bd58d9f02b5f26126aaa2a21cf309ad4db16ddb7e1a503f549116c51abb04a1d98fbb15c6aa5a4c3eaec",
  "TopicArn" : "arn:aws:sns:us-west-2:276428873250:magine-qa",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-west-2:276428873250:magine-qa.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:276428873250:magine-qa&Token=2336412f37fb687f5d51e6e241dbca52e6afbffe988721d9c64b3691091f6078cb23594fa041543a4154a271d741e3d679257f3e6a814696f4adae1715dda06f91c6bf50a1d6bd58d9f02b5f26126aaa2a21cf309ad4db16ddb7e1a503f549116c51abb04a1d98fbb15c6aa5a4c3eaec",
  "Timestamp" : "2019-09-30T16:01:17.704Z",
  "SignatureVersion" : "1",
  "Signature" : "JcZk8WJ6QrOZEvo8oxrrADumCyuX4S4JHOrqxXlwF9YolnEclm1y5g0uJeEjS+Gj7076cGPetgCygzXXDamPDaiZOOfrIoZ/4a9fyEfiNopP6iyu02tO+TmMpSk+pOQ+jlGxUTTKWKTzQoeq2LPXxfekKERSMuyd0WQIyrPJUSrvcjinTSwyZhrdHy9xHP92HbGhXWNY+O1yPdvSpBDCcOIOfNAlLmNP6mLRVvajV1mkgWHuQfeiZnPTOmAGTGGoYFFoxmvbxNRPOnfBo6Xv67zHYknhED9LBZZiWax3grhySekk3p8fxDzuV1vW7L80yDmNrgxC1RC34HCvUmCLSA==",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-6aad65c2f9911b05cd53efda11f913f9.pem"
}
[2019-09-30T16:01:17.861Z] error TypeError: Cannot destructure property `types` of 'undefined' or 'null'.
    at Object.update (/app/strapi/plugins/magine/services/Magine.js:61:9)
    at update (/app/strapi/plugins/magine/controllers/Magine.js:37:62)
    at dispatch (/app/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/app/strapi/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at dispatch (/app/strapi/node_modules/koa-compose/index.js:42:32)
    at policies.push (/app/strapi/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:28)
    at dispatch (/app/strapi/node_modules/koa-compose/index.js:42:32)
    at RateLimit._rateLimit (/app/strapi/node_modules/koa2-ratelimit/src/RateLimit.js:187:16)
```

**Comment by KempfCreative** [comment]
ah, I think what is happening is that the code for this endpoint is primed to work with the actual payload with image data, but since this is the initial payload request, it fails! Let me check.
